### PR TITLE
Use gettext with help strings

### PR DESCRIPTION
**Pull request by mdellweg**
[noissue]

### CODE REVIEW

**Review by daviddavis — APPROVED** [review]
:man_dancing:

**Comment by daviddavis** [comment]
Actually, why not do like we do in pulpcore?

```
from gettext import gettext as _
```

**Comment by mdellweg** [comment]
I was reading more and more, and i think we want to use the class based approach.
So ATM even `_ = lambda (s): s` would to the trick.
I think, i want to setup `_` in every plugins `__init__` and import it from there.

**Comment by mdellweg** [comment]
> I think, i want to setup `_` in every plugins `__init__` and import it from there.

Nope, circular dependency. We could use the `translation.install()` method. But we would need to find a way to merge the plugins translations into the global table. :exploding_head:

**Comment by mdellweg** [comment]
I'm going to merge it as is, to get us in `_`-land soon. We will need to find a proper way to install the translation catalogs later.

**Pull request merged**
