### PR TITLE
Add global show command

### PR DESCRIPTION
**Pull request by daviddavis**
fixes #8063

### CODE REVIEW

**Comment by daviddavis** [comment]
There is an alternative implementation that I debated that is very simple and requires no change to openapi. It's a hack though. Would be something like:

```python
@click.command(name="show")
@click.option("--href", required=True, help="HREF of the entry")
@pass_pulp_context
def show(pulp_ctx: PulpContext, href: str) -> None:
    """Show a resource given its href."""
    entity = pulp_ctx.api.show("artifacts_read", parameters={"artifact_href": href})
    pulp_ctx.output_result(entity)
```

**Comment by ipanova** [comment]
what is the benefit of using cli to display an href `pulp show --href <href>` over pure http GET <href> ?

**Comment by daviddavis** [comment]
@ipanova I think the long term goal of the CLI is to make httpie irrelevant so that most likely users won’t have it installed or configured.

**Comment by mdellweg** [comment]
> what is the benefit of using cli to display an href `pulp show --href <href>` over pure `http GET <href> ` ?

Well, it stays in the tool; it reuses the config set for the cli; it can benefit from output formatting.

**Comment by mdellweg** [comment]
> There is an alternative implementation that I debated that is very simple and requires no change to openapi. It's a hack though. Would be something like:
> 
> ```python
> @click.command(name="show")
> @click.option("--href", required=True, help="HREF of the entry")
> @pass_pulp_context
> def show(pulp_ctx: PulpContext, href: str) -> None:
>     """Show a resource given its href."""
>     entity = pulp_ctx.api.show("artifacts_read", parameters={"artifact_href": href})
>     pulp_ctx.output_result(entity)
> ```

Yeah, i, too, have been thinking of just using the existing artifact operation. My second implementation idea however was to inject a new fake operation into the json-api before parsing it. This might actually be the method that would not stop working, if we ever decide to api conform response parsing.

**Comment by daviddavis** [comment]
> My second implementation idea however was to inject a new fake operation into the json-api before parsing it. This might actually be the method that would not stop working, if we ever decide to api conform response parsing.

Hmm, that's an interesting idea. I'm happy to switch this to artfiact read and then we can later perhaps switch it to this fake operation?

**Comment by mdellweg** [comment]
That sounds like a plan!

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
