### PR TITLE
0.5.0 release

### PR DESCRIPTION
**Pull request by daviddavis**

### CODE REVIEW

**Comment by mdellweg** [comment]
I see you are planning a release here. Is this urgent?
I really want to have #153 in a release ASAP.
@bmbouter is working on it.
That said, the release process is easy enough to release a 0.6.0 for just this. If we want to get other things out now.

**Comment by daviddavis** [comment]
Was thinking about it. The migration PRs are blocked until we release the migration support and releasing would make it easier for Katello to test it out too.

When do you estimate #153 will be done? As you say, a 0.6.0 release is easy and I’m happy to do it in a few days.

**Review by mdellweg — APPROVED** [review]
I have no good estimate, so I'd say go ahead.

**Comment by mdellweg** [comment]
Can you move the remaining stuff to a new milestone?

**Comment by daviddavis** [comment]
I moved the remaining issues to a new 0.6.0 milestone and closed out 0.5.0.

**Pull request merged**
