### PR TITLE
Test Pulp against a rerouted container

### LINKED ISSUE #465: Refactor: add needs_capability to context
## Summary

We should have a needs_capability that raises itself.
Rationale: All mentions of Pulp versions should be in context.py.

See attached PR for an example of what we could move into context

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by mdellweg** [comment]
Hmmm ... docker with, work it does not.

**Comment by ipanova** [comment]
> Hmmm ... docker with, work it does not.

what docker say does?

**Comment by mdellweg** [comment]
> > Hmmm ... docker with, work it does not.
> 
> what docker say does?

My `--env` argument ignoring docker is.

**Review by fao89 — APPROVED** [review]
LGTM

**Pull request merged**
