### PR TITLE
Disable sending telemetry in CI

### PR DESCRIPTION
**Pull request by mdellweg**
cc @bmbouter

### CODE REVIEW

**Review by bmbouter — APPROVED** [review]
I'm not sure how we're going to CI this feature overall. I guess the best idea would be to write unit tests? I guess we should approve this. Let's get another LGTM from someone in telemetry then, @ggainey @ipanova @dkliban wdyt?

**Comment by bmbouter** [comment]
I disabled TELEMETRY for all repos via [this plugin template change](https://github.com/pulp/plugin_template/pull/690). Do you think this PR is still needed?

**Comment by mdellweg** [comment]
Absolutely

**Comment by bmbouter** [comment]
> Absolutely

It seems they both are setting the same setting though. Is the setting not applying in the same way here or something?

**Pull request merged**
