### PR TITLE
Pin schema due to breakage in 0.7.6.

### PR DESCRIPTION
**Pull request by ggainey**
Example:
```
~ $ pip install schema
...
Successfully installed contextlib2-21.6.0 schema-0.7.6 ~ $ python3
>>> import schema as s
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'schema'
>>>
```

[noissue]

Review Checklist:
- [ ] An issue is properly linked. [feature and bugfix only]
- [ ] Tests are present or not feasible.
- [ ] Commits are split in a logical way (not historically).

### CODE REVIEW

**Comment by ggainey** [comment]
may just close this, schema yanked 0.7.6

**Comment by ggainey** [comment]
schema yanked their broken version and we seem to be fine (for now) - closing this PR

**Comment by mdellweg** [comment]
Actually, instead of pinning, I would have preferred to opt the broken version out (like `...,!=0.7.6`).

**Comment by ggainey** [comment]
At the time, I couldn't predict the maintainer's future stance, and our PR/CI?Release processes were all blocked. The pin was an immediate bandaid :)  Fortunately, the maintainer responded quickly

**Pull request closed without merging**
