### PR TITLE
Add an URL entry to the package info.

### LINKED ISSUE #148: Please add a link to GH on the pypi page
I think it would be nice to add a link  to https://github.com/pulp/pulp-cli on https://pypi.org/project/pulp-cli.

### PR DESCRIPTION
**Pull request by thmo**
This should fix #148.

### CODE REVIEW

**Comment by daviddavis** [comment]
Can you add "[noissue]" to your commit?

**Comment by mdellweg** [comment]
Instead of [noissue] it should be `fixes #148` on a separate line

**Comment by thmo** [comment]
> Instead of [noissue] it should be `fixes #148` on a separate line

Done :)

**Review by daviddavis — APPROVED** [review]

**Review by mdellweg — APPROVED** [review]
Thank you!

**Pull request merged**
