### PR TITLE
Improve error reporting from openapi calls

### PR DESCRIPTION
**Pull request by mdellweg**
In case the library can identify the error, there is no use in dumping a
complete stack trace. Introduced OpenAPIError exception.

### CODE REVIEW

**Review by daviddavis — APPROVED** [review]

**Comment by daviddavis** [comment]
FYI, I started looking at the failures. They're also happening on develop. I couldn't reproduce locally though with my dev server. I think there might be something in the single container that's causing the failures...?

**Comment by mdellweg** [comment]
I added more error output on failed tasks. So in a way, we were lucky here. XD
https://github.com/pulp/pulp-cli/pull/21/checks?check_run_id=1304812030#step:6:224

**Comment by daviddavis** [comment]
Here we go: 

https://github.com/aio-libs/aiohttp/issues/5110 
https://github.com/aio-libs/aiohttp/pull/5118

**Comment by daviddavis** [comment]
I opened https://github.com/pulp/pulpcore/pull/984 so we're not completely unpinned.

I also kicked off a new pulp-oci-images publish job.

**Comment by mdellweg** [comment]
So it has been fixed upstream... ?!

**Pull request merged**
