### PR TITLE
relax PyYAML and requests deps

### PR DESCRIPTION
**Pull request by evgeni**
let's assume they know how semver works

[noissue]

### CODE REVIEW

**Review by pcreech — APPROVED** [review]

**Comment by pcreech** [comment]
Oops, didn't realize this was on the overall pulp-cli repo.  Apologies for the errant approval.

**Comment by daviddavis** [comment]
I think this will trigger dependabot to attempt to update the dependencies. Might be good to add [a dependabot ignore rule](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#creating-ignore-conditions-from-dependabot-ignore).

**Comment by evgeni** [comment]
> I think this will trigger dependabot to attempt to update the dependencies. Might be good to add [a dependabot ignore rule](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#creating-ignore-conditions-from-dependabot-ignore).

Will it? There are no newer PyYAML or requests that don't match the version range *today*, so I am not sure to what it would try to update to. And if there will be, it might be a good trigger to re-consider the version range?

**Comment by daviddavis** [comment]
Yea, I believe dependabot will bump the floor even if the requirement doesn't preclude the new release version. Here's an example:

https://github.com/pulp/pulpcore/pull/1462

**Comment by daviddavis** [comment]
We could just ignore the dependabot PRs for these deps. We might forget though so it might make sense to leave a comment.

**Comment by mdellweg** [comment]
Let's merge this, and see what dependabot has to offer. WDYT?

**Comment by evgeni** [comment]
Works for me!

**Comment by daviddavis** [comment]
Me too :+1:

**Review by mdellweg — APPROVED** [review]

**Pull request merged**
