### PR TITLE
Python remote packages can be specified with requirements.txt files

### PR DESCRIPTION
**Pull request by gerrod3**
fixes: #240

### CODE REVIEW

**Comment by mdellweg** [comment]
I'm not in the position to decide, whether it would be a good idea, to let the API itself to understand such requirements files, but have you considered using an existing parsing function like here: https://stackoverflow.com/a/59971236 ?

**Comment by gerrod3** [comment]
> I'm not in the position to decide, whether it would be a good idea, to let the API itself to understand such requirements files, but have you considered using an existing parsing function like here: https://stackoverflow.com/a/59971236 ?

I thought about it, but using the parsing function would prevent using requirements files that are conglomerates of other requirements files.  The only parsing that is being done here is removing spaces and comments, the rest of the validation is still done by the API.

**Comment by dralley** [comment]
@gerrod3  This looks good in terms of implementation, my only concern is whether we want to support not just requirements files but also .lock files for package managers like Poetry and Pipenv.  And maybe a user a user would want to add more than one requirements.txt.

**Review by dralley — APPROVED** [review]

**Review by mdellweg — APPROVED** [review]
@dralley thanks for looking!
Making your review official.

**Pull request merged**
