### PR TITLE
Support for mirror flag when syncing rpm repositories

### PR DESCRIPTION
**Pull request by vonsch**
[noissue]

### CODE REVIEW

**Comment by vonsch** [comment]
Btw I also considered if it would be better to use ```--mirror/--no-mirror``` python click options instead of ```--mirror True```/```--mirror False```, but not sure what's better.

**Comment by mdellweg** [comment]
We use `--bool/--no-bool` everywhere else.

**Comment by vonsch** [comment]
@mdellweg thanks for suggestion, I modified PR

**Review by mdellweg — APPROVED** [review]
@daviddavis do you think, we need a changelog here?

**Comment by daviddavis** [comment]
I don't see the harm in adding a changelog. It's good to always call out new additions.

That said, I have no objection to not having a changelog either.

**Comment by vonsch** [comment]
@mdellweg If prefer to have changelog entry, I can easily add one. However if I understand the ```CHANGES/``` directory layout and file naming well, I must first create some github issue and then reference it in the ```CHANGES/<issue_number>.feature, right?

**Comment by daviddavis** [comment]
You could just use this PR number (ie `CHANGES/212.feature`).

**Comment by vonsch** [comment]
@daviddavis ok, added

**Review by mdellweg — APPROVED** [review]
Thank you very much!

**Pull request merged**
