### PR TITLE
Use PluginRequirement for has/needs_plugin

### PR DESCRIPTION
**Pull request by mdellweg**
[noissue]

### CODE REVIEW

**Comment by daviddavis** [comment]
This code looks good to me. I'm interested though in why this keeps support for plugin/min_version/max_version instead of just standardizing on using PluginRequirement?

**Comment by mdellweg** [comment]
Because there is at least one plugin out of this tree using it.

**Comment by daviddavis** [comment]
Thank you, makes sense. Is the plan to keep plugin/min_version/max_version around permanently or temporarily?

**Review by daviddavis — APPROVED** [review]
This lgtm. 👍

**Comment by mdellweg** [comment]
> Thank you, makes sense. Is the plan to keep plugin/min_version/max_version around permanently or temporarily?

I hope temporarily.

**Pull request merged**
