### PR TITLE
Add task-group command group

### PR DESCRIPTION
**Pull request by mdellweg**
[noissue]

### CODE REVIEW

**Review by daviddavis — APPROVED** [review]
I was going to ask about tests but I suppose the method for generating task groups (via pulp import) doesn't exist.

**Comment by mdellweg** [comment]
> I was going to ask about tests but I suppose the method for generating task groups (via pulp import) doesn't exist.

Yep, exactly.

**Comment by mdellweg** [comment]
But you may ask for a changelog...

**Comment by daviddavis** [comment]
Can we get a changelog entry? :smile:

**Review by daviddavis — APPROVED** [review]

**Pull request merged**
